### ISSUE TITLE
Push notifications are not working

### ISSUE THREAD

**Issue by OmalPerera** [OmalPerera/Mini-Project-CIS#2]
When ever try to integrate push notifications following errors prompts in logcat

    java.lang.NoSuchMethodError: com.google.firebase.iid.FirebaseInstanceIdInternalReceiver.zzUr
                                                      at com.google.firebase.messaging.FirebaseMessagingService.zzz(Unknown Source)
                                                      at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
                                                      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2805)
                                                      at android.app.ActivityThread.access$1900(ActivityThread.java:156)
                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                      at android.os.Looper.loop(Looper.java:153)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                      at dalvik.system.NativeStart.main(Native Method)

[http://stackoverflow.com/questions/38200664/firebase-messaging-nosuchmethoderror-zzur-exception](http://stackoverflow.com/questions/38200664/firebase-messaging-nosuchmethoderror-zzur-exception)

**Comment by OmalPerera** [comment]
Issue solved 
Probable reasons could be 

    - compile 'com.firebase:firebase-client-android:2.3.1'
    - compile 'com.google.android.gms:play-services-gcm:9.0.0'
    - compile 'com.google.firebase:firebase-core:9.2.0'

using above libraries in the app level gradle.
